Red Step a new TDD cycle write a new failing test inside CitySearch.test.js that uses user-event
Added two new tests for clarity
1. One that checks that the suggestion list is hidden by default
2. One that clicks the input and expects the list to become visible.
3. Confirm the failure by run npm test :
TestingLibraryElementError: Unable to find an accessible element with the role "list"
Test Suites 1 Failed, 2 Passed , 3 total
Tests 1 Failed, 6 Passed, 7 Total